on: [push]

jobs:
  testjob:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'push-to-changelog'

      - name: Release
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filePath: './push-to-changelog/CHANGELOG.md'
